CREATE TABLE MASTER (IDMASTER INTEGER NOT NULL, USERNAME VARCHAR, iddetail VARCHAR, PRIMARY KEY (IDMASTER))
CREATE TABLE DETAIL (IDDETAIL INTEGER NOT NULL, CITY VARCHAR, POSTALCODE VARCHAR, idmaster VARCHAR, PRIMARY KEY (IDDETAIL))
CREATE SEQUENCE MASTER_SEQ;
CREATE SEQUENCE DETAIL_SEQ;